In [1]:
# If you are working with a shape file stored in google drive remove the quotes (""" """)

"""
#connect with drive
from google.colab import drive
drive.mount('/content/drive')
"""

"\n#connect with drive\nfrom google.colab import drive\ndrive.mount('/content/drive')\n"

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# If you are using other folder distribution or drive modify here your path:
path = ''

# MPM dataframe

In [4]:
mpm_df = pd.read_csv(path + 'Medida De Pobreza Multidimensional (MPM) - Dane/MPM_Output/mpm_data_dane_2018.csv')
mpm_df = mpm_df.drop(['Unnamed: 0', 'DPTO_CCDGO', 'MPIO_CNMBR', 'MPIO_CCNCT', 'DPTO_CNMBR'], axis=1)
mpm_df.head()

,MPM,MPM_CAB,MPM_CPRD,AFBMO_TOT,AFBMO_CAB,AFBMO_CPRD,BLE_TOT,BLE_CAB,BLE_CPRD,BSCPI_TOT,...,SAS_TOT,SAS_CAB,SAS_CPRD,TRINF_TOT,TRINF_CAB,TRINF_CPRD,TRIML_TOT,TRIML_CAB,TRIML_CPRD,Municipality code
0,29.6,27.2,53.3,9.1,8.4,16.7,47.8,45.5,73.6,2.3,...,20.4,20.5,19.0,1.4,1.2,3.3,85.0,84.4,91.5,18001
1,38.8,26.6,48.9,12.1,9.1,14.8,68.7,58.6,77.6,1.1,...,12.0,11.7,12.3,1.9,1.6,2.2,88.1,85.5,90.4,18029
2,50.0,41.4,66.1,18.4,16.8,21.8,67.5,60.7,81.4,2.7,...,16.6,16.7,16.4,1.9,1.1,3.7,88.6,87.0,92.0,18094
3,44.3,37.6,60.7,14.7,13.5,18.1,68.2,62.8,82.6,1.8,...,14.1,14.4,13.5,1.9,1.3,3.7,90.7,89.3,94.4,18247
4,45.5,40.3,53.4,14.7,15.0,14.2,72.5,66.0,81.3,1.8,...,12.7,12.9,12.5,2.6,2.3,2.9,90.0,87.6,93.4,18256

In [5]:
mpm_df['State code'] = mpm_df['Municipality code'].apply(lambda x: int(str(x)[:-3]))
mpm_df['cod_mun'] = mpm_df['Municipality code'].apply(lambda x: int(str(x)[-3:]))
mpm_df.head()

,MPM,MPM_CAB,MPM_CPRD,AFBMO_TOT,AFBMO_CAB,AFBMO_CPRD,BLE_TOT,BLE_CAB,BLE_CPRD,BSCPI_TOT,...,SAS_CPRD,TRINF_TOT,TRINF_CAB,TRINF_CPRD,TRIML_TOT,TRIML_CAB,TRIML_CPRD,Municipality code,State code,cod_mun
0,29.6,27.2,53.3,9.1,8.4,16.7,47.8,45.5,73.6,2.3,...,19.0,1.4,1.2,3.3,85.0,84.4,91.5,18001,18,1
1,38.8,26.6,48.9,12.1,9.1,14.8,68.7,58.6,77.6,1.1,...,12.3,1.9,1.6,2.2,88.1,85.5,90.4,18029,18,29
2,50.0,41.4,66.1,18.4,16.8,21.8,67.5,60.7,81.4,2.7,...,16.4,1.9,1.1,3.7,88.6,87.0,92.0,18094,18,94
3,44.3,37.6,60.7,14.7,13.5,18.1,68.2,62.8,82.6,1.8,...,13.5,1.9,1.3,3.7,90.7,89.3,94.4,18247,18,247
4,45.5,40.3,53.4,14.7,15.0,14.2,72.5,66.0,81.3,1.8,...,12.5,2.6,2.3,2.9,90.0,87.6,93.4,18256,18,256

In [6]:
mpm_df.shape

(1122, 51)

# Sociodemographic dataframe

In [7]:
sociodemographic_df = pd.read_csv(path + "Datos Sociodemograficos/DANE_Sociodemograficos.csv")
sociodemographic_df = sociodemographic_df.drop(['Cases 2015', 'Cases 2016', 'Cases 2017', 'Cases 2018', 'Cases 2019'], 1)
sociodemographic_df['cod_mun'] = sociodemographic_df['Municipality code'].apply(lambda x: int(str(x)[-3:]))
sociodemographic_df

,State code,State,Municipality code,Municipality,Population 2015,Population 2016,Population 2017,Population 2018,Population 2019,Age 0-4 (%),...,Households without internet access (%),Building stratification 1 (%),Building stratification 2 (%),Building stratification 3 (%),Building stratification 4 (%),Building stratification 5 (%),Building stratification 6 (%),Number of hospitals per Km2,Number of houses per Km2,cod_mun
0,5,Antioquia,5001,Medellín,2431666,2420516,2414616,2427129,2483545,5.16,...,29.47,12.1117,31.2817,26.0471,9.0279,6.4855,3.7062,1.555263,2102.057895,1
1,5,Antioquia,5002,Abejorral,19897,19979,20047,20367,20258,5.24,...,56.27,31.3520,33.8306,2.0439,0.0352,0.0117,0.0000,0.002012,11.945674,2
2,5,Antioquia,5004,Abriaquí,2514,2539,2593,2695,2710,6.07,...,62.35,21.5705,39.1675,4.3519,0.0946,0.1892,0.1892,0.000000,2.548276,4
3,5,Antioquia,5021,Alejandría,4511,4543,4570,4657,4669,6.59,...,54.61,17.9879,38.5721,4.8215,0.1854,0.0464,0.0464,0.006623,9.092715,21
4,5,Antioquia,5030,Amagá,28691,29006,29429,30227,30777,5.42,...,56.12,27.8784,42.0280,3.4086,0.1889,0.1460,0.0172,0.011765,102.752941,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,97,Vaupés,97889,Yavaraté,1212,1073,1027,1048,1067,5.03,...,75.76,6.0606,1.0101,0.0000,0.0000,0.0000,0.0000,0.000000,0.028621,889
1118,99,Vichada,99001,Puerto Carreño,20319,20921,21087,20936,20474,10.61,...,68.68,41.0368,15.3779,2.4037,0.0579,0.0145,0.0145,0.000388,0.432426,1
1119,99,Vichada,99524,La Primavera,9694,10098,10233,10122,9799,10.37,...,72.64,39.3295,5.0284,0.7782,0.0299,0.0000,0.0000,0.000000,0.113272,524
1120,99,Vichada,99624,Santa Rosalía,4551,4296,4083,4059,4130,9.34,...,81.35,50.2627,7.0053,0.2627,0.0000,0.0000,0.0000,0.000254,0.247904,624
1121,99,Vichada,99773,Cumaribo,51719,57693,65161,72691,76196,14.09,...,86.83,10.5047,0.4311,0.1998,0.0000,0.0000,0.0000,0.000061,0.134017,773

# Sivigila Dataframe
* <a href="https://www.ins.gov.co/Transparencia/informacion-de-interes/Paginas/Datos-Abiertos.aspx"> Datos abiertos Sivigila</a>
* <a href="http://portalsivigila.ins.gov.co/Paginas/Vigilancia-Rutinaria.aspx?GroupString=%3B%23Descargar%3A%202007%202019p%3B%23&IsGroupRender=TRUE"> Estadísticas de Vigilancia Rutinaria Sivigila</a>


* 'BAJO PESO AL NACER' in: 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019
* 'MORTALIDAD POR DESNUTRICIÓN' in: 2013, 2014, 2015, 2016, 2017, 2018, 2019
* 'DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS' in: 2016, 2017, 2018, 2019

In [8]:
path_sivigila = path + 'Sivigilia/Data/'

In [9]:
# Read xls file 
# Data from 2007 - 2011 commented because is not used
#sivigila_2007 = pd.read_excel(path_sivigila + '/content/drive/MyDrive/Nutrición/HealthDataPython/Sivigilia/rutinaria_2007.xlsx', sheet_name=3)
#sivigila_2008 = pd.read_excel(path_sivigila + '/content/drive/MyDrive/Nutrición/HealthDataPython/Sivigilia/rutinaria_2008.xlsx', sheet_name=3)
#sivigila_2009 = pd.read_excel(path_sivigila + '/content/drive/MyDrive/Nutrición/HealthDataPython/Sivigilia/rutinaria_2009.xlsx', sheet_name=3)
#sivigila_2010 = pd.read_excel(path_sivigila + '/content/drive/MyDrive/Nutrición/HealthDataPython/Sivigilia/rutinaria_2010.xlsx', sheet_name=3)
#sivigila_2011 = pd.read_excel(path_sivigila + '/content/drive/MyDrive/Nutrición/HealthDataPython/Sivigilia/rutinaria_2011.xlsx', sheet_name=3)
sivigila_2012 = pd.read_excel(path_sivigila + 'rutinaria_2012.xlsx', sheet_name=3)
sivigila_2013 = pd.read_excel(path_sivigila + 'rutinaria_2013.xlsx', sheet_name=3)
sivigila_2014 = pd.read_excel(path_sivigila + 'rutinaria_2014.xlsx', sheet_name=3)
sivigila_2015 = pd.read_excel(path_sivigila + 'rutinaria_2015.xlsx', sheet_name=3)
sivigila_2016 = pd.read_excel(path_sivigila + 'rutinaria_2016.xlsx', sheet_name=3)
sivigila_2017 = pd.read_excel(path_sivigila + 'rutinaria_2017.xlsx', sheet_name=3)
sivigila_2018 = pd.read_excel(path_sivigila + 'rutinaria_2018.xlsx', sheet_name=3)
#sivigila_2019_2 = pd.read_excel('/content/drive/MyDrive/Nutrición/HealthDataPython/Sivigilia/rutinaria_2019.xlsx', sheet_name=2, skiprows=[0, 1, 2])
#sivigila_2019_2['NOM_EVE'] = sivigila_2019_2['NOM_EVE'].fillna(method='ffill')


# Read CSV file
sivigila_2017_2 = pd.read_csv(path_sivigila + "SIVIGILA_2017.csv")
sivigila_2018_2 = pd.read_csv(path_sivigila + "SIVIGILA_2018.csv")
sivigila_2019 = pd.read_csv(path_sivigila + "SIVIGILA_2019.csv")

### 2012

In [10]:
sivigila_2012 = sivigila_2012.drop(['Semana_', 'Departamento'], axis=1)
sivigila_2012.columns = ['cod_eve', 'Nombre', 'State code', 'cod_mun', 'nom_mun', 'SEMANA', 'ANO', 'conteo_casos']
sivigila_2012['Municipality code'] = sivigila_2012['cod_mun']
sivigila_2012['cod_mun'] = sivigila_2012['cod_mun'].apply(lambda x: int(str(x)[-3:]))
sivigila_2012.head()

# cod_eve	Nombre	ANO	SEMANA	State code	nom_mun	cod_mun	conteo_casos

,cod_eve,Nombre,State code,cod_mun,nom_mun,SEMANA,ANO,conteo_casos,Municipality code
0,560,MORTALIDAD PERINATAL Y NEONATAL TARDÍA,52,696,SANTA BARBARA (ISCUANDE),26,2012,1,52696
1,420,LEISHMANIASIS CUTANEA,41,551,PITALITO,5,2012,1,41551
2,735,ANOMALIAS CONGENITAS,5,148,CARMEN DE VIBORAL,32,2012,1,5148
3,455,LEPTOSPIROSIS,66,456,MISTRATO,41,2012,2,66456
4,620,PAROTIDITIS,25,885,YACOPI,29,2012,1,25885

### 2013

In [11]:
sivigila_2013 = sivigila_2013.drop(['semana_', 'Departamento'], axis=1)
sivigila_2013.columns = ['cod_eve', 'Nombre', 'State code', 'cod_mun', 'nom_mun', 'SEMANA', 'ANO', 'conteo_casos']
sivigila_2013['Municipality code'] = sivigila_2013['cod_mun']
sivigila_2013['cod_mun'] = sivigila_2013['cod_mun'].apply(lambda x: int(str(x)[-3:]))
sivigila_2013.head()

# cod_eve	Nombre	ANO	SEMANA	State code	nom_mun	cod_mun	conteo_casos

,cod_eve,Nombre,State code,cod_mun,nom_mun,SEMANA,ANO,conteo_casos,Municipality code
0,110,BAJO PESO AL NACER,5,0,* ANTIOQUIA. MUNICIPIO DESCONOCIDO,29,2013,1,5000
1,735,ANOMALIAS CONGENITAS,13,244,EL CARMEN DE BOLIVAR,7,2013,1,13244
2,300,AGRESIONES POR ANIMALES POTENCIALMENTE TRANSMI...,19,137,CALDONO,39,2013,1,19137
3,300,AGRESIONES POR ANIMALES POTENCIALMENTE TRANSMI...,15,646,SAMACA,34,2013,2,15646
4,210,DENGUE,73,408,LERIDA,38,2013,7,73408

### 2014

In [12]:
sivigila_2014 = sivigila_2014.drop(['semana_', 'Departamento'], axis=1)
sivigila_2014.columns = ['cod_eve', 'Nombre', 'State code', 'cod_mun', 'nom_mun', 'SEMANA', 'ANO', 'conteo_casos']
sivigila_2014['Municipality code'] = sivigila_2014['cod_mun']
sivigila_2014['cod_mun'] = sivigila_2014['cod_mun'].apply(lambda x: int(str(x)[-3:]))
sivigila_2014.head()

# cod_eve	Nombre	ANO	SEMANA	State code	nom_mun	cod_mun	conteo_casos

,cod_eve,Nombre,State code,cod_mun,nom_mun,SEMANA,ANO,conteo_casos,Municipality code
0,110,BAJO PESO AL NACER,86,219,COLON,14,2014,1,86219
1,110,BAJO PESO AL NACER,86,1,MOCOA,15,2014,2,86001
2,110,BAJO PESO AL NACER,86,320,ORITO,15,2014,1,86320
3,110,BAJO PESO AL NACER,86,573,PUERTO LEGUIZAMO,17,2014,1,86573
4,110,BAJO PESO AL NACER,86,568,PUERTO ASIS,26,2014,1,86568

### 2015

In [13]:
sivigila_2015 = sivigila_2015.drop(['Semana_', 'Departamento'], axis=1)
sivigila_2015.columns = ['cod_eve', 'Nombre', 'State code', 'cod_mun', 'nom_mun', 'SEMANA', 'ANO', 'conteo_casos']
sivigila_2015['Municipality code'] = sivigila_2015['cod_mun']
sivigila_2015['cod_mun'] = sivigila_2015['cod_mun'].apply(lambda x: int(str(x)[-3:]))
sivigila_2015.head()

# cod_eve	Nombre	ANO	SEMANA	State code	nom_mun	cod_mun	conteo_casos

,cod_eve,Nombre,State code,cod_mun,nom_mun,SEMANA,ANO,conteo_casos,Municipality code
0,100,ACCIDENTE OFIDICO,54,720,SARDINATA,49,2015,1,54720
1,100,ACCIDENTE OFIDICO,54,245,EL CARMEN,52,2015,1,54245
2,100,ACCIDENTE OFIDICO,66,383,LA CELIA,2,2015,1,66383
3,100,ACCIDENTE OFIDICO,66,572,PUEBLO RICO,8,2015,3,66572
4,100,ACCIDENTE OFIDICO,66,572,PUEBLO RICO,13,2015,1,66572

### 2016

In [14]:
sivigila_2016 = sivigila_2016.drop(['semana_', 'Departamento'], axis=1)
sivigila_2016.columns = ['cod_eve', 'Nombre', 'State code', 'cod_mun', 'nom_mun', 'SEMANA', 'ANO', 'conteo_casos']
sivigila_2016['Municipality code'] = sivigila_2016['cod_mun']
sivigila_2016['cod_mun'] = sivigila_2016['cod_mun'].apply(lambda x: int(str(x)[-3:]))
sivigila_2016.head()

# cod_eve	Nombre	ANO	SEMANA	State code	nom_mun	cod_mun	conteo_casos

,cod_eve,Nombre,State code,cod_mun,nom_mun,SEMANA,ANO,conteo_casos,Municipality code
0,155,CÁNCER DE LA MAMA Y CUELLO UTERINO,47,0,* MAGDALENA. MUNICIPIO DESCONOCIDO,34,2016,1,47000
1,113,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,52,473,MOSQUERA,21,2016,1,52473
2,113,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,52,835,TUMACO,25,2016,1,52835
3,113,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,52,693,SAN PABLO,27,2016,1,52693
4,113,DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS,52,678,SAMANIEGO,30,2016,3,52678

### 2017

In [15]:
sivigila_2017 = sivigila_2017.drop(['TITULO_SEMANA', 'Departamento'], axis=1)
sivigila_2017.columns = ['cod_eve', 'Nombre', 'SEMANA', 'ANO', 'State code', 'cod_mun', 'nom_mun', 'conteo_casos']
sivigila_2017['Municipality code'] = sivigila_2017['cod_mun']
sivigila_2017['cod_mun'] = sivigila_2017['cod_mun'].apply(lambda x: int(str(x)[-3:]))
sivigila_2017.head()

,cod_eve,Nombre,SEMANA,ANO,State code,cod_mun,nom_mun,conteo_casos,Municipality code
0,875,VCM VIF VSX,1,2017,99,773,CUMARIBO,2,99773
1,560,MORTALIDAD PERINATAL Y NEONATAL TARDÍA,26,2017,99,773,CUMARIBO,1,99773
2,875,VCM VIF VSX,6,2017,99,773,CUMARIBO,1,99773
3,470,MALARIA FALCIPARUM,29,2017,99,624,SANTA ROSALIA,1,99624
4,875,VCM VIF VSX,52,2017,99,773,CUMARIBO,1,99773

### 2018

In [16]:
sivigila_2018 = sivigila_2018.drop(['Titulo_semana', 'Departamento', 'mun'], axis=1)
# cod_eve	Nombre	ANO	SEMANA	State code	nom_mun	cod_mun	conteo_casos
sivigila_2018.columns = ['cod_eve', 'Nombre', 'SEMANA', 'nom_mun', 'conteo_casos', 'State code', 'cod_mun']
sivigila_2018 = sivigila_2018.assign(ANO=2018)
sivigila_2018['Municipality code'] = sivigila_2018['cod_mun']
sivigila_2018['cod_mun'] = sivigila_2018['cod_mun'].apply(lambda x: int(str(x)[-3:]))
sivigila_2018.head()

,cod_eve,Nombre,SEMANA,nom_mun,conteo_casos,State code,cod_mun,ANO,Municipality code
0,100,ACCIDENTE OFIDICO,1,TENERIFE,1,47,798,2018,47798
1,100,ACCIDENTE OFIDICO,1,GIRON,1,68,307,2018,68307
2,100,ACCIDENTE OFIDICO,2,PAZ DE ARIPORO,1,85,250,2018,85250
3,100,ACCIDENTE OFIDICO,2,RIOSUCIO,3,27,615,2018,27615
4,100,ACCIDENTE OFIDICO,2,CIENAGA,1,47,189,2018,47189

### 2019

In [17]:
sivigila_2017_2 = sivigila_2017_2.rename(columns={'cod_dpto': 'State code'})
sivigila_2019.columns = sivigila_2017_2.columns
sivigila_2019

,cod_eve,Nombre,ANO,SEMANA,State code,nom_mun,cod_mun,conteo_casos
0,100,ACCIDENTE OFIDICO,2019,1,5,EL BAGRE,250,2
1,100,ACCIDENTE OFIDICO,2019,1,5,MUTATA,480,1
2,100,ACCIDENTE OFIDICO,2019,1,5,YARUMAL,887,1
3,100,ACCIDENTE OFIDICO,2019,1,8,GALAPA,296,1
4,100,ACCIDENTE OFIDICO,2019,1,13,ARJONA,52,1
...,...,...,...,...,...,...,...,...
205527,895,ZIKA,2019,50,8,BARRANQUILLA,1,1
205528,895,ZIKA,2019,50,73,SUAREZ,770,1
205529,895,ZIKA,2019,50,76,CALI,1,2
205530,895,ZIKA,2019,51,94,PUERTO INIRIDA,1,1
205531,895,ZIKA,2019,52,20,SAN ALBERTO,710,1

In [18]:
municipality_code_df = pd.read_csv(path_sivigila + "DIVIPOLA_Municipios.csv", sep=';', encoding='latin1')
municipality_code_df = municipality_code_df.rename(columns={'COD_MPIO': 'Municipality code', 'COD_DPTO': 'State code'})
municipality_code_df = municipality_code_df.drop(['NOM_DPTO', 'NOM_MPIO', 'TIPO', 'LATITUD', 'LONGITUD'], axis=1)
municipality_code_df['cod_mun'] = municipality_code_df['Municipality code'].apply(lambda x: int(str(x)[-3:]))
municipality_code_df

      State code  Municipality code  cod_mun
0              5               5001        1
1              5               5002        2
2              5               5004        4
3              5               5021       21
4              5               5030       30
...          ...                ...      ...
1116          97              97889      889
1117          99              99001        1
1118          99              99524      524
1119          99              99624      624
1120          99              99773      773

[1121 rows x 3 columns]

In [19]:
sivigila_2019 = sivigila_2019.merge(municipality_code_df, on=['State code', 'cod_mun'], how='inner')
sivigila_2019

,cod_eve,Nombre,ANO,SEMANA,State code,nom_mun,cod_mun,conteo_casos,Municipality code
0,100,ACCIDENTE OFIDICO,2019,1,5,EL BAGRE,250,2,5250
1,100,ACCIDENTE OFIDICO,2019,2,5,EL BAGRE,250,1,5250
2,100,ACCIDENTE OFIDICO,2019,5,5,EL BAGRE,250,1,5250
3,100,ACCIDENTE OFIDICO,2019,4,5,EL BAGRE,250,1,5250
4,100,ACCIDENTE OFIDICO,2019,8,5,EL BAGRE,250,1,5250
...,...,...,...,...,...,...,...,...,...
203048,875,VCM VIF VSX,2019,33,91,PUERTO ARICA (CD),536,1,91536
203049,875,VCM VIF VSX,2019,3,91,PUERTO ARICA (CD),536,1,91536
203050,875,VCM VIF VSX,2019,30,91,PUERTO ARICA (CD),536,2,91536
203051,490,MALARIA VIVAX,2019,51,91,PUERTO ALEGRIA (CD),530,1,91530
203052,875,VCM VIF VSX,2019,44,91,PUERTO ALEGRIA (CD),530,1,91530

In [20]:
def df_to_colum(df_disease, disiese, year):
  # From week 1 to week 52
  for i in range(1,53):
    # If is the 1st week we need to create the new data frame
    if (i == 1):
      # Take from df_disiese rows with week 01
      cases_week_df = df_disease[df_disease.SEMANA == i][['Municipality code', 'State code', 'cod_mun', 'conteo_casos']]
      # Rename cases column with the year and week information
      cases_week_df = cases_week_df.rename(columns={'conteo_casos': 'cases_'+ disiese + '_' + str(year) + '_week_0' + str(i)})
    elif (i < 10):
      # Take from df_disiese rows with week 02 .. 09 in an auxiliar df
      cases_week_df_aux = df_disease[df_disease.SEMANA == i][['Municipality code', 'State code', 'cod_mun', 'conteo_casos']]
      # Rename cases column with the year and week information
      cases_week_df_aux = cases_week_df_aux.rename(columns={'conteo_casos': 'cases_'+ disiese + '_' + str(year) + '_week_0' + str(i)})
      # Merge the new auxiliar df with the df with past weeks outer, so we doesn't loose new municipalities
      cases_week_df = cases_week_df.merge(cases_week_df_aux, on=['Municipality code', 'State code', 'cod_mun'], how='outer')
    else:
      # Take from df_disiese rows with week 10 ... 52 in an auxiliar df
      cases_week_df_aux = df_disease[df_disease.SEMANA == i][['Municipality code', 'State code', 'cod_mun', 'conteo_casos']]
      # Rename cases column with the year and week information
      cases_week_df_aux = cases_week_df_aux.rename(columns={'conteo_casos': 'cases_'+ disiese + '_' + str(year) + '_week_' + str(i)})
      # Merge the new auxiliar df with the df with past weeks outer, so we doesn't loose new municipalities
      #cases2017_week_df = pd.concat([cases2017_week_df, cases2017_week_df_aux], join="outer")
      cases_week_df = cases_week_df.merge(cases_week_df_aux, on=['Municipality code', 'State code', 'cod_mun'], how='outer')
  disease_cases_week_df = cases_week_df.fillna(0)
  return disease_cases_week_df

In [21]:
def merge_two_df(df1, df2, how = 'outer'):
  df3 = df1.merge(df2, on=['Municipality code', 'State code', 'cod_mun'], how=how)
  df3 = df3.fillna(0)
  return df3

In [22]:
def get_Desnutricion_df(sivigila_df):
  # Get year
  year = int(pd.unique(sivigila_df.ANO))
  if (year >= 2016):

    # Get dataframe of 'MORTALIDAD POR DESNUTRICIÓN'
    df_disease = sivigila_df[sivigila_df.Nombre == 'MORTALIDAD POR DESNUTRICIÓN']
    # Extract all cases as a new column
    disease_cases_week_df_1 = df_to_colum(df_disease, 'MortalidadDesnutricion', year)
    # Get dataframe of 'DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS'
    df_disease = sivigila_df[sivigila_df.Nombre == 'DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS']
    # Extract all cases as a new column
    disease_cases_week_df_2 = df_to_colum(df_disease, 'DesnutricionMenores5', year)
    
    # Merge 'MORTALIDAD POR DESNUTRICIÓN' and 'DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS'
    cases_week_df = merge_two_df(disease_cases_week_df_1, disease_cases_week_df_2)

  elif (year >= 2013 and year < 2016):

    # Get dataframe of 'MORTALIDAD POR DESNUTRICIÓN'
    df_disease = sivigila_df[sivigila_df.Nombre == 'MORTALIDAD POR DESNUTRICIÓN']
    # Extract all cases as a new column and Return this values
    cases_week_df = df_to_colum(df_disease, 'MortalidadDesnutricion', year)

  return cases_week_df

In [23]:
desnutricion_2017 = get_Desnutricion_df(sivigila_2017)
desnutricion_2018 = get_Desnutricion_df(sivigila_2018)
desnutricion_2019 = get_Desnutricion_df(sivigila_2019)
#desnutricion_2017.shape
desnutricion_2017.head()

,Municipality code,State code,cod_mun,cases_MortalidadDesnutricion_2017_week_01,cases_MortalidadDesnutricion_2017_week_02,cases_MortalidadDesnutricion_2017_week_03,cases_MortalidadDesnutricion_2017_week_04,cases_MortalidadDesnutricion_2017_week_05,cases_MortalidadDesnutricion_2017_week_06,cases_MortalidadDesnutricion_2017_week_07,...,cases_DesnutricionMenores5_2017_week_43,cases_DesnutricionMenores5_2017_week_44,cases_DesnutricionMenores5_2017_week_45,cases_DesnutricionMenores5_2017_week_46,cases_DesnutricionMenores5_2017_week_47,cases_DesnutricionMenores5_2017_week_48,cases_DesnutricionMenores5_2017_week_49,cases_DesnutricionMenores5_2017_week_50,cases_DesnutricionMenores5_2017_week_51,cases_DesnutricionMenores5_2017_week_52
0,91000,91,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,44560,44,560,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,1.0,3.0,3.0,2.0,5.0,5.0,2.0,3.0
2,27450,27,450,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,20013,20,13,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,3.0,0.0,1.0,3.0,0.0,0.0,1.0
4,5234,5,234,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [24]:
def get_two_Desnutricion_dfs(sivigila_df):
  # Get year
  year = int(pd.unique(sivigila_df.ANO))
  if (year >= 2016):
    # Get dataframe of 'MORTALIDAD POR DESNUTRICIÓN'
    df_disease = sivigila_df[sivigila_df.Nombre == 'MORTALIDAD POR DESNUTRICIÓN']
    # Extract all cases as a new column
    disease_cases_week_df_1 = df_to_colum(df_disease, 'MortalidadDesnutricion', year)
    # Get dataframe of 'DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS'
    df_disease = sivigila_df[sivigila_df.Nombre == 'DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS']
    # Extract all cases as a new column
    disease_cases_week_df_2 = df_to_colum(df_disease, 'DesnutricionMenores5', year)
    
    # Return two dfs
    return disease_cases_week_df_1, disease_cases_week_df_2
  
  elif (year >= 2013 and year < 2016):
    # Get dataframe of 'MORTALIDAD POR DESNUTRICIÓN'
    df_disease = sivigila_df[sivigila_df.Nombre == 'MORTALIDAD POR DESNUTRICIÓN']
    # Extract all cases as a new column
    disease_cases_week_df_1 = df_to_colum(df_disease, 'MortalidadDesnutricion', year)
    
    # Return two dfs
    return disease_cases_week_df_1
  else:
    pass

In [25]:
mortalidad_desnutricion_2013  = get_two_Desnutricion_dfs(sivigila_2013)
print(f'the shape of mortalidad desnutrición 2013 is {mortalidad_desnutricion_2013.shape}')
mortalidad_desnutricion_2014  = get_two_Desnutricion_dfs(sivigila_2014)
print(f'the shape of mortalidad desnutrición 2014 is {mortalidad_desnutricion_2014.shape}')
mortalidad_desnutricion_2015  = get_two_Desnutricion_dfs(sivigila_2015)
print(f'the shape of mortalidad desnutrición 2015 is {mortalidad_desnutricion_2015.shape}')
mortalidad_desnutricion_2016, desnutricion_menores5_2016  = get_two_Desnutricion_dfs(sivigila_2016)
print(f'the shape of mortalidad desnutrición 2016 is {mortalidad_desnutricion_2016.shape} and shape of desnutrición menores de 5 is {desnutricion_menores5_2016.shape}')
mortalidad_desnutricion_2017, desnutricion_menores5_2017  = get_two_Desnutricion_dfs(sivigila_2017)
print(f'the shape of mortalidad desnutrición 2017 is {mortalidad_desnutricion_2017.shape} and shape of desnutrición menores de 5 is {desnutricion_menores5_2017.shape}')
mortalidad_desnutricion_2018, desnutricion_menores5_2018  = get_two_Desnutricion_dfs(sivigila_2018)
print(f'the shape of mortalidad desnutrición 2018 is {mortalidad_desnutricion_2018.shape} and shape of desnutrición menores de 5 is {desnutricion_menores5_2018.shape}')
mortalidad_desnutricion_2019, desnutricion_menores5_2019  = get_two_Desnutricion_dfs(sivigila_2019)
print(f'the shape of mortalidad desnutrición 2019 is {mortalidad_desnutricion_2019.shape} and shape of desnutrición menores de 5 is {desnutricion_menores5_2019.shape}')
mortalidad_desnutricion_2013

the shape of mortalidad desnutrición 2013 is (107, 55)
the shape of mortalidad desnutrición 2014 is (163, 55)
the shape of mortalidad desnutrición 2015 is (121, 55)
the shape of mortalidad desnutrición 2016 is (122, 55) and shape of desnutrición menores de 5 is (682, 55)
the shape of mortalidad desnutrición 2017 is (120, 55) and shape of desnutrición menores de 5 is (813, 55)
the shape of mortalidad desnutrición 2018 is (108, 55) and shape of desnutrición menores de 5 is (898, 55)
the shape of mortalidad desnutrición 2019 is (107, 55) and shape of desnutrición menores de 5 is (904, 55)

,Municipality code,State code,cod_mun,cases_MortalidadDesnutricion_2013_week_01,cases_MortalidadDesnutricion_2013_week_02,cases_MortalidadDesnutricion_2013_week_03,cases_MortalidadDesnutricion_2013_week_04,cases_MortalidadDesnutricion_2013_week_05,cases_MortalidadDesnutricion_2013_week_06,cases_MortalidadDesnutricion_2013_week_07,...,cases_MortalidadDesnutricion_2013_week_43,cases_MortalidadDesnutricion_2013_week_44,cases_MortalidadDesnutricion_2013_week_45,cases_MortalidadDesnutricion_2013_week_46,cases_MortalidadDesnutricion_2013_week_47,cases_MortalidadDesnutricion_2013_week_48,cases_MortalidadDesnutricion_2013_week_49,cases_MortalidadDesnutricion_2013_week_50,cases_MortalidadDesnutricion_2013_week_51,cases_MortalidadDesnutricion_2013_week_52
0,19364,19,364,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,76054,76,54,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,44560,44,560,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
3,11001,11,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0
4,76001,76,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,91263,91,263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
103,23417,23,417,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
104,66687,66,687,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
105,25743,25,743,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
106,27615,27,615,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [26]:
desnutricion_menores5_2019

,Municipality code,State code,cod_mun,cases_DesnutricionMenores5_2019_week_01,cases_DesnutricionMenores5_2019_week_02,cases_DesnutricionMenores5_2019_week_03,cases_DesnutricionMenores5_2019_week_04,cases_DesnutricionMenores5_2019_week_05,cases_DesnutricionMenores5_2019_week_06,cases_DesnutricionMenores5_2019_week_07,...,cases_DesnutricionMenores5_2019_week_43,cases_DesnutricionMenores5_2019_week_44,cases_DesnutricionMenores5_2019_week_45,cases_DesnutricionMenores5_2019_week_46,cases_DesnutricionMenores5_2019_week_47,cases_DesnutricionMenores5_2019_week_48,cases_DesnutricionMenores5_2019_week_49,cases_DesnutricionMenores5_2019_week_50,cases_DesnutricionMenores5_2019_week_51,cases_DesnutricionMenores5_2019_week_52
0,5480,5,480,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20001,20,1,2.0,2.0,5.0,5.0,1.0,2.0,3.0,...,4.0,9.0,3.0,5.0,7.0,2.0,2.0,2.0,2.0,2.0
2,41396,41,396,1.0,1.0,0.0,1.0,2.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0
3,50001,50,1,5.0,2.0,1.0,5.0,3.0,3.0,2.0,...,2.0,1.0,2.0,1.0,1.0,2.0,0.0,1.0,1.0,0.0
4,52835,52,835,4.0,1.0,2.0,2.0,2.0,3.0,10.0,...,4.0,5.0,6.0,4.0,2.0,3.0,4.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899,97777,97,777,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
900,25596,25,596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
901,50686,50,686,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
902,52885,52,885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
903,70508,70,508,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [27]:
def merge_desnuticion_dfs(desnutricion_dfs):
  for i in range(len(desnutricion_dfs)-1):
    if (i == 0):
      merged_df = merge_two_df(desnutricion_dfs[i], desnutricion_dfs[i+1])  
    else:
      merged_df = merge_two_df(merged_df, desnutricion_dfs[i+1]) 
  return merged_df

### 'MORTALIDAD POR DESNUTRICIÓN'

In [28]:
desnutricion_dfs = [mortalidad_desnutricion_2013, mortalidad_desnutricion_2014, mortalidad_desnutricion_2015, mortalidad_desnutricion_2016, mortalidad_desnutricion_2017, mortalidad_desnutricion_2018, mortalidad_desnutricion_2019]
mortalidad_desnutricion = merge_desnuticion_dfs(desnutricion_dfs)
mortalidad_desnutricion

,Municipality code,State code,cod_mun,cases_MortalidadDesnutricion_2013_week_01,cases_MortalidadDesnutricion_2013_week_02,cases_MortalidadDesnutricion_2013_week_03,cases_MortalidadDesnutricion_2013_week_04,cases_MortalidadDesnutricion_2013_week_05,cases_MortalidadDesnutricion_2013_week_06,cases_MortalidadDesnutricion_2013_week_07,...,cases_MortalidadDesnutricion_2019_week_43,cases_MortalidadDesnutricion_2019_week_44,cases_MortalidadDesnutricion_2019_week_45,cases_MortalidadDesnutricion_2019_week_46,cases_MortalidadDesnutricion_2019_week_47,cases_MortalidadDesnutricion_2019_week_48,cases_MortalidadDesnutricion_2019_week_49,cases_MortalidadDesnutricion_2019_week_50,cases_MortalidadDesnutricion_2019_week_51,cases_MortalidadDesnutricion_2019_week_52
0,19364,19,364,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,76054,76,54,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,44560,44,560,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,11001,11,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,76001,76,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,73675,73,675,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
359,66001,66,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
360,17042,17,42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
361,23678,23,678,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
362,54820,54,820,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

### DESNUTRICIÓN AGUDA EN MENORES DE 5 AÑOS

In [29]:
desnutricion_dfs = [desnutricion_menores5_2016, desnutricion_menores5_2017, desnutricion_menores5_2018, desnutricion_menores5_2019]
desnutricion_menores5 = merge_desnuticion_dfs(desnutricion_dfs)
desnutricion_menores5

,Municipality code,State code,cod_mun,cases_DesnutricionMenores5_2016_week_01,cases_DesnutricionMenores5_2016_week_02,cases_DesnutricionMenores5_2016_week_03,cases_DesnutricionMenores5_2016_week_04,cases_DesnutricionMenores5_2016_week_05,cases_DesnutricionMenores5_2016_week_06,cases_DesnutricionMenores5_2016_week_07,...,cases_DesnutricionMenores5_2019_week_43,cases_DesnutricionMenores5_2019_week_44,cases_DesnutricionMenores5_2019_week_45,cases_DesnutricionMenores5_2019_week_46,cases_DesnutricionMenores5_2019_week_47,cases_DesnutricionMenores5_2019_week_48,cases_DesnutricionMenores5_2019_week_49,cases_DesnutricionMenores5_2019_week_50,cases_DesnutricionMenores5_2019_week_51,cases_DesnutricionMenores5_2019_week_52
0,8001,8,1,5.0,3.0,5.0,5.0,7.0,2.0,3.0,...,3.0,6.0,5.0,3.0,6.0,2.0,2.0,1.0,5.0,5.0
1,25288,25,288,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,41378,41,378,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,41001,41,1,3.0,1.0,6.0,4.0,9.0,6.0,1.0,...,5.0,2.0,1.0,2.0,5.0,0.0,3.0,4.0,1.0,1.0
4,44001,44,1,2.0,2.0,0.0,0.0,0.0,3.0,2.0,...,6.0,4.0,6.0,8.0,8.0,9.0,11.0,5.0,6.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,54480,54,480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1076,17388,17,388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1077,5467,5,467,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1078,15131,15,131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1079,50686,50,686,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Merge all in desnutricion_df

In [30]:
desnutricion_df = merge_two_df(desnutricion_menores5, mortalidad_desnutricion)
desnutricion_df

,Municipality code,State code,cod_mun,cases_DesnutricionMenores5_2016_week_01,cases_DesnutricionMenores5_2016_week_02,cases_DesnutricionMenores5_2016_week_03,cases_DesnutricionMenores5_2016_week_04,cases_DesnutricionMenores5_2016_week_05,cases_DesnutricionMenores5_2016_week_06,cases_DesnutricionMenores5_2016_week_07,...,cases_MortalidadDesnutricion_2019_week_43,cases_MortalidadDesnutricion_2019_week_44,cases_MortalidadDesnutricion_2019_week_45,cases_MortalidadDesnutricion_2019_week_46,cases_MortalidadDesnutricion_2019_week_47,cases_MortalidadDesnutricion_2019_week_48,cases_MortalidadDesnutricion_2019_week_49,cases_MortalidadDesnutricion_2019_week_50,cases_MortalidadDesnutricion_2019_week_51,cases_MortalidadDesnutricion_2019_week_52
0,8001,8,1,5.0,3.0,5.0,5.0,7.0,2.0,3.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,25288,25,288,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,41378,41,378,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,41001,41,1,3.0,1.0,6.0,4.0,9.0,6.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,44001,44,1,2.0,2.0,0.0,0.0,0.0,3.0,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1079,50686,50,686,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1080,95000,95,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1081,52352,52,352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1082,91263,91,263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1083,25841,25,841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
municipality_code_df = pd.read_csv(path_sivigila + "DIVIPOLA_Municipios.csv", sep=';', encoding='latin1')
municipality_code_df = municipality_code_df.rename(columns={'COD_MPIO': 'Municipality code', 'COD_DPTO': 'State code', 'NOM_MPIO': 'Municipio', 'NOM_DPTO': 'Departamento' })
municipality_code_df = municipality_code_df.drop(['TIPO', 'LATITUD', 'LONGITUD', 'State code'], axis=1)
municipality_code_df

     Departamento  Municipality code       Municipio
0       ANTIOQUIA               5001        MEDELLÍN
1       ANTIOQUIA               5002       ABEJORRAL
2       ANTIOQUIA               5004        ABRIAQUÍ
3       ANTIOQUIA               5021      ALEJANDRÍA
4       ANTIOQUIA               5030           AMAGÁ
...           ...                ...             ...
1116       VAUPÉS              97889        YAVARATÉ
1117      VICHADA              99001  PUERTO CARREÑO
1118      VICHADA              99524    LA PRIMAVERA
1119      VICHADA              99624   SANTA ROSALÍA
1120      VICHADA              99773        CUMARIBO

[1121 rows x 3 columns]

In [32]:
desnutricion_df = municipality_code_df.merge(desnutricion_df, on=['Municipality code'], how='inner')
desnutricion_df

,Departamento,Municipality code,Municipio,State code,cod_mun,cases_DesnutricionMenores5_2016_week_01,cases_DesnutricionMenores5_2016_week_02,cases_DesnutricionMenores5_2016_week_03,cases_DesnutricionMenores5_2016_week_04,cases_DesnutricionMenores5_2016_week_05,...,cases_MortalidadDesnutricion_2019_week_43,cases_MortalidadDesnutricion_2019_week_44,cases_MortalidadDesnutricion_2019_week_45,cases_MortalidadDesnutricion_2019_week_46,cases_MortalidadDesnutricion_2019_week_47,cases_MortalidadDesnutricion_2019_week_48,cases_MortalidadDesnutricion_2019_week_49,cases_MortalidadDesnutricion_2019_week_50,cases_MortalidadDesnutricion_2019_week_51,cases_MortalidadDesnutricion_2019_week_52
0,ANTIOQUIA,5001,MEDELLÍN,5,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ANTIOQUIA,5002,ABEJORRAL,5,2,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ANTIOQUIA,5030,AMAGÁ,5,30,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ANTIOQUIA,5031,AMALFI,5,31,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ANTIOQUIA,5034,ANDES,5,34,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042,VAUPÉS,97889,YAVARATÉ,97,889,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1043,VICHADA,99001,PUERTO CARREÑO,99,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1044,VICHADA,99524,LA PRIMAVERA,99,524,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1045,VICHADA,99624,SANTA ROSALÍA,99,624,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1046,VICHADA,99773,CUMARIBO,99,773,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

# WorldClim (Temperature, Precipitation, Elevation)

## Precipitation

In [33]:
# Read precipitation csv file to dataframe
path_worldclim = path + 'Satelital Data/WorldClim Data/'
wclim_precipitation = pd.read_csv(path_worldclim + 'precipitation2007_2018.csv',encoding="latin1")
# Remove extra column
wclim_precipitation = wclim_precipitation.drop('Unnamed: 0', 1)
wclim_precipitation

,PRECIPITATION_dec_07,PRECIPITATION_nov_07,PRECIPITATION_oct_07,PRECIPITATION_sep_07,PRECIPITATION_aug_07,PRECIPITATION_jul_07,PRECIPITATION_jun_07,PRECIPITATION_may_07,PRECIPITATION_apr_07,PRECIPITATION_mar_07,...,PRECIPITATION_mar_18,PRECIPITATION_feb_18,PRECIPITATION_jan_18,COD_DPTO,NOM_DPTO,COD_MPIO,NOM_MPIO,TIPO,LATITUD,LONGITUD
0,184.041061,275.321289,320.929840,234.679382,230.007416,386.515533,157.963028,345.532501,291.927124,195.452469,...,140.323318,86.131554,131.176727,5,ANTIOQUIA,5001,MEDELLIN,Municipio,6.257590,-75.611031
1,188.846893,273.956421,306.016602,198.806503,245.224106,337.009155,145.024872,368.622955,298.137146,211.111679,...,145.937302,107.644608,151.625977,5,ANTIOQUIA,5002,ABEJORRAL,Municipio,5.803728,-75.438474
2,156.805939,258.298187,263.346008,242.937805,221.506516,422.573364,152.230927,334.840881,246.919952,152.713318,...,111.904190,69.363213,98.848007,5,ANTIOQUIA,5004,ABRIAQUI,Municipio,6.627569,-76.085978
3,171.435532,285.962006,361.769562,243.856186,324.082489,339.436737,161.073792,345.874695,286.881470,199.928375,...,147.506775,86.449814,140.216995,5,ANTIOQUIA,5021,ALEJANDRIA,Municipio,6.365534,-75.090597
4,198.276825,279.687347,283.321747,214.617142,210.302658,350.168793,143.757507,350.666260,288.957397,166.522003,...,117.747261,91.315475,123.736755,5,ANTIOQUIA,5030,AMAGA,Municipio,6.032922,-75.708003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,264.013519,212.278305,279.244720,190.655624,278.347107,342.514343,342.738068,381.056885,452.434814,239.813202,...,252.428787,231.900406,202.577591,97,VAUPES,97889,YAVARATE,Área no municipalizada,0.833312,-69.618678
1117,173.103867,29.344395,269.728882,230.292145,421.836273,382.576141,548.346130,300.548218,118.855217,74.337234,...,50.140205,24.139158,15.195719,99,VICHADA,99001,PUERTO CARRENO,Municipio,5.836530,-68.141222
1118,151.401306,72.124481,241.255753,237.114182,411.128052,319.890625,490.604065,352.242706,171.536575,72.397057,...,65.763680,20.500990,16.264862,99,VICHADA,99524,LA PRIMAVERA,Municipio,5.517594,-69.620441
1119,88.122917,123.080513,268.816803,253.235947,373.553619,317.735199,495.871796,352.469208,233.093735,86.531944,...,76.090843,25.839094,20.919085,99,VICHADA,99624,SANTA ROSALIA,Municipio,4.968581,-70.659971
1120,215.295837,79.886940,250.194077,262.958557,319.148987,328.944000,491.006195,348.101105,191.018372,98.048576,...,109.150352,49.677608,36.773026,99,VICHADA,99773,CUMARIBO,Municipio,4.262455,-69.521405

In [34]:
## each year has 12 months -> for loop test for month and year
months=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']
years =['12','13','14','15','16','17','18']
columns_order_prec=[]
for year in years:
  for i in range (0,12):    ##0-11
     columns_order_prec.append('PRECIPITATION_' + months[i] + '_' + year)
columns_order_prec.extend( ['COD_DPTO',
 'NOM_DPTO',
 'COD_MPIO',
 'NOM_MPIO',
 'TIPO',
 'LATITUD',
 'LONGITUD'])
#columns_order_prec

In [35]:
#re-assign ordered columns to dataframe
wclim_precipitation = wclim_precipitation[columns_order_prec]
wclim_precipitation = wclim_precipitation.rename(columns={'COD_MPIO': 'Municipality code', 'COD_DPTO': 'State code', 'NOM_MPIO': 'Municipio', 'NOM_DPTO': 'Departamento' })
wclim_precipitation = wclim_precipitation.drop(['TIPO', 'LATITUD', 'LONGITUD'], axis=1)
wclim_precipitation

,PRECIPITATION_jan_12,PRECIPITATION_feb_12,PRECIPITATION_mar_12,PRECIPITATION_apr_12,PRECIPITATION_may_12,PRECIPITATION_jun_12,PRECIPITATION_jul_12,PRECIPITATION_aug_12,PRECIPITATION_sep_12,PRECIPITATION_oct_12,...,PRECIPITATION_jul_18,PRECIPITATION_aug_18,PRECIPITATION_sep_18,PRECIPITATION_oct_18,PRECIPITATION_nov_18,PRECIPITATION_dec_18,State code,Departamento,Municipality code,Municipio
0,143.996338,84.448479,182.468307,333.664246,231.788162,155.533585,157.200623,197.431381,156.635132,292.931702,...,180.841248,200.803131,294.888611,302.151306,276.914551,67.528000,5,ANTIOQUIA,5001,MEDELLIN
1,160.942566,106.062065,195.236008,335.972321,235.506897,137.339874,145.540436,196.814590,120.980026,262.268219,...,171.043686,202.056366,263.658752,274.999481,276.055359,60.356739,5,ANTIOQUIA,5002,ABEJORRAL
2,111.156319,63.352127,139.529083,264.172241,224.507599,161.450974,144.373047,223.425888,152.721695,258.622406,...,160.006393,216.341446,273.485809,267.168549,257.440796,63.571411,5,ANTIOQUIA,5004,ABRIAQUI
3,150.545135,83.663269,196.101776,379.806580,250.881134,147.830139,170.156113,242.204559,193.028320,368.291504,...,195.619019,256.421906,302.413086,353.701385,277.470184,61.464046,5,ANTIOQUIA,5021,ALEJANDRIA
4,134.874725,88.863426,153.000458,319.132904,227.482208,141.205353,139.597794,180.010681,133.121002,248.926941,...,162.015167,182.192062,274.654327,259.078125,282.538574,68.923813,5,ANTIOQUIA,5030,AMAGA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,246.043457,293.505249,407.725311,365.653198,392.213135,293.933899,397.901672,235.901962,277.331238,205.193298,...,439.042084,259.967499,228.402420,219.714844,321.411407,278.270264,97,VAUPES,97889,YAVARATE
1117,4.852512,64.169716,19.765818,137.477249,358.253082,463.689972,443.183502,301.246613,368.370850,154.864349,...,415.627289,356.083832,289.744232,203.861130,113.063705,46.351234,99,VICHADA,99001,PUERTO CARRENO
1118,8.818299,24.708885,37.555386,201.510422,316.493896,396.162323,365.600647,335.368958,302.225433,195.043701,...,368.413727,398.009094,273.555542,227.666840,138.658142,56.324593,99,VICHADA,99524,LA PRIMAVERA
1119,17.106863,27.472258,71.874939,257.697968,307.460052,447.773102,332.031342,314.011322,258.444458,252.859131,...,355.766449,350.775452,260.249359,276.039124,126.202217,55.008774,99,VICHADA,99624,SANTA ROSALIA
1120,21.897491,38.989922,60.883514,170.462570,267.397003,380.227905,344.382019,312.029022,322.393250,196.578659,...,358.986816,367.327606,304.344543,259.568573,148.708694,82.457962,99,VICHADA,99773,CUMARIBO

## Temperature

In [36]:
# Read precipitation csv file to dataframe
wclim_temperature = pd.read_csv(path_worldclim + 'tempearture2007-2018.csv',encoding="latin1")
# Remove extra column
wclim_temperature = wclim_temperature.drop('Unnamed: 0', 1)
wclim_temperature

,TEMPERATURE_dec_07,TEMPERATURE_nov_07,TEMPERATURE_oct_07,TEMPERATURE_sep_07,TEMPERATURE_aug_07,TEMPERATURE_jul_07,TEMPERATURE_jun_07,TEMPERATURE_may_07,TEMPERATURE_apr_07,TEMPERATURE_mar_07,...,TEMPERATURE_mar_18,TEMPERATURE_feb_18,TEMPERATURE_jan_18,COD_DPTO,NOM_DPTO,COD_MPIO,NOM_MPIO,TIPO,LATITUD,LONGITUD
0,20.200329,20.165262,19.954406,20.705536,20.866394,21.686978,21.243176,21.322522,21.237032,21.425911,...,21.726171,21.180842,20.979769,5,ANTIOQUIA,5001,MEDELLIN,Municipio,6.257590,-75.611031
1,15.875682,15.932109,15.558375,16.318124,16.154948,16.738302,16.744885,16.764218,16.592266,16.853578,...,17.169984,16.587068,16.455098,5,ANTIOQUIA,5002,ABEJORRAL,Municipio,5.803728,-75.438474
2,16.393875,16.418080,16.142443,16.753113,16.717581,17.557740,17.357063,17.461414,17.463490,17.444237,...,17.833994,17.157058,17.019929,5,ANTIOQUIA,5004,ABRIAQUI,Municipio,6.627569,-76.085978
3,19.881327,20.018971,19.855212,20.499266,20.634999,21.333450,21.114738,21.331241,21.113854,21.210392,...,21.489558,20.862208,20.606707,5,ANTIOQUIA,5021,ALEJANDRIA,Municipio,6.365534,-75.090597
4,19.933408,19.881884,19.706597,20.407709,20.447760,21.281823,20.900712,21.174519,21.144019,21.328261,...,21.648314,20.980035,20.688046,5,ANTIOQUIA,5030,AMAGA,Municipio,6.032922,-75.708003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,25.871243,25.967607,25.762292,25.766627,25.017467,24.929709,25.064161,25.452312,26.150623,26.316475,...,26.505539,26.463302,25.843567,97,VAUPES,97889,YAVARATE,Área no municipalizada,0.833312,-69.618678
1117,28.490139,28.584764,27.976620,27.368171,27.009569,27.086235,27.334923,28.358616,29.317689,30.537816,...,29.914727,29.510480,28.883538,99,VICHADA,99001,PUERTO CARRENO,Municipio,5.836530,-68.141222
1118,27.834608,27.915222,27.312293,27.085120,26.512006,26.743574,26.635199,27.578315,28.325781,29.480690,...,29.391974,29.062382,28.382773,99,VICHADA,99524,LA PRIMAVERA,Municipio,5.517594,-69.620441
1119,27.091002,27.198468,26.599324,26.433393,25.768856,25.887431,25.773636,26.854834,27.563194,28.733139,...,28.906054,28.652033,27.769912,99,VICHADA,99624,SANTA ROSALIA,Municipio,4.968581,-70.659971
1120,26.976658,27.121646,26.504748,26.466948,25.886993,26.062330,25.971426,26.823096,27.297660,28.200171,...,28.155295,28.122336,27.411737,99,VICHADA,99773,CUMARIBO,Municipio,4.262455,-69.521405

In [37]:
## each year has 12 months -> for loop test for month and year
months=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']
years =['12','13','14','15','16','17','18']
columns_order_temp=[]
for year in years:
  for i in range (0,12):    ##0-11
      columns_order_temp.append('TEMPERATURE_' + months[i] + '_' + year)
columns_order_temp.extend( ['COD_DPTO',
 'NOM_DPTO',
 'COD_MPIO',
 'NOM_MPIO',
 'TIPO',
 'LATITUD',
 'LONGITUD'])
#columns_order_temp

In [38]:
#re-assign ordered columns to dataframe
wclim_temperature = wclim_temperature[columns_order_temp]
wclim_temperature = wclim_temperature.rename(columns={'COD_MPIO': 'Municipality code', 'COD_DPTO': 'State code', 'NOM_MPIO': 'Municipio', 'NOM_DPTO': 'Departamento' })
wclim_temperature = wclim_temperature.drop(['TIPO', 'LATITUD', 'LONGITUD'], axis=1)
wclim_temperature

,TEMPERATURE_jan_12,TEMPERATURE_feb_12,TEMPERATURE_mar_12,TEMPERATURE_apr_12,TEMPERATURE_may_12,TEMPERATURE_jun_12,TEMPERATURE_jul_12,TEMPERATURE_aug_12,TEMPERATURE_sep_12,TEMPERATURE_oct_12,...,TEMPERATURE_jul_18,TEMPERATURE_aug_18,TEMPERATURE_sep_18,TEMPERATURE_oct_18,TEMPERATURE_nov_18,TEMPERATURE_dec_18,State code,Departamento,Municipality code,Municipio
0,21.288711,20.828412,21.272264,20.995364,21.537712,21.759842,22.085763,21.765526,21.631403,20.921942,...,21.952168,21.719432,21.347202,20.748416,20.886703,20.936353,5,ANTIOQUIA,5001,MEDELLIN
1,16.819161,16.280817,16.763734,16.254766,16.979062,17.347229,17.171114,17.082292,17.242343,16.556031,...,17.063302,17.103385,17.011875,16.495094,16.674297,16.627245,5,ANTIOQUIA,5002,ABEJORRAL
2,17.249878,16.763655,17.329046,17.259671,17.633376,17.875988,18.013209,17.535202,17.711794,17.122912,...,17.843157,17.512112,17.356325,16.911367,17.231535,17.080420,5,ANTIOQUIA,5004,ABRIAQUI
3,20.927366,20.578701,21.117597,20.931043,21.533325,21.683661,21.849336,21.553924,21.587722,20.846706,...,21.652374,21.425886,21.230342,20.725872,20.687894,20.574121,5,ANTIOQUIA,5021,ALEJANDRIA
4,21.034401,20.598786,21.167064,20.848186,21.360716,21.432744,21.667760,21.350625,21.280364,20.682899,...,21.560988,21.380573,21.026458,20.558420,20.625113,20.717262,5,ANTIOQUIA,5030,AMAGA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,26.478203,25.891427,25.854496,25.588122,25.480437,25.640723,25.003148,25.346633,26.003606,26.212031,...,25.008356,25.352882,26.116107,26.381042,26.529586,26.300149,97,VAUPES,97889,YAVARATE
1117,29.539789,29.610481,29.716984,28.446856,27.433355,27.272249,27.336236,27.199152,27.655670,28.357871,...,26.794482,27.001324,27.557754,27.757870,28.391361,28.290137,99,VICHADA,99001,PUERTO CARRENO
1118,29.073224,29.003181,29.019404,27.648265,27.117465,26.912628,26.841057,26.894123,27.339287,27.904394,...,26.470571,26.864957,27.489720,27.587379,28.106454,28.010822,99,VICHADA,99524,LA PRIMAVERA
1119,28.347602,28.510106,28.441732,26.978038,26.489988,26.300718,26.093681,26.305141,26.970545,27.312693,...,25.822849,26.348023,27.013428,27.146027,27.544563,27.512444,99,VICHADA,99624,SANTA ROSALIA
1120,28.186738,28.019472,27.749218,26.746706,26.375353,26.301374,26.183337,26.149494,26.793857,27.155530,...,25.908164,26.096456,26.865039,26.887561,27.399683,27.309817,99,VICHADA,99773,CUMARIBO

## Elevation

In [39]:
# Read elevation csv file to dataframe  
wlcim_elevation = pd.read_csv(path_worldclim + 'elevation.csv', encoding="latin1")
# Remove extra column
wlcim_elevation = wlcim_elevation.drop('Unnamed: 0', 1)
wlcim_elevation = wlcim_elevation.rename(columns={'COD_MPIO': 'Municipality code', 'COD_DPTO': 'State code', 'NOM_MPIO': 'Municipio', 'NOM_DPTO': 'Departamento' })
wlcim_elevation = wlcim_elevation.drop(['TIPO', 'LATITUD', 'LONGITUD'], axis=1)
wlcim_elevation['cod_mun'] = wlcim_elevation['Municipality code'].apply(lambda x: int(str(x)[-3:]))

wlcim_elevation = wlcim_elevation[['State code',	'Departamento',	'Municipality code', 'cod_mun',	'Municipio', 'Elevation']]
wlcim_elevation

,State code,Departamento,Municipality code,cod_mun,Municipio,Elevation
0,5,ANTIOQUIA,5001,1,MEDELLIN,1650.0
1,5,ANTIOQUIA,5002,2,ABEJORRAL,2150.0
2,5,ANTIOQUIA,5004,4,ABRIAQUI,2162.0
3,5,ANTIOQUIA,5021,21,ALEJANDRIA,1612.0
4,5,ANTIOQUIA,5030,30,AMAGA,1537.0
...,...,...,...,...,...,...
1116,97,VAUPES,97889,889,YAVARATE,163.0
1117,99,VICHADA,99001,1,PUERTO CARRENO,66.0
1118,99,VICHADA,99524,524,LA PRIMAVERA,98.0
1119,99,VICHADA,99624,624,SANTA ROSALIA,142.0
1120,99,VICHADA,99773,773,CUMARIBO,159.0

### Merge WorldClim Data (Precipitation + Temperature + Elevation)

In [40]:
# merge temperature + precipitation using 'COD_DPTO',	'NOM_DPTO',	'COD_MPIO',	'NOM_MPIO',	'TIPO',	'LATITUD',	'LONGITUD'
worldclim_df = wclim_precipitation.merge(wclim_temperature, on=['State code',	'Departamento',	'Municipality code',	'Municipio'], how='inner')
# merge temperature + precipitation + elevation 'COD_DPTO',	'NOM_DPTO',	'COD_MPIO',	'NOM_MPIO',	'TIPO',	'LATITUD',	'LONGITUD'
worldclim_df = wlcim_elevation.merge(worldclim_df, on=['State code',	'Departamento',	'Municipality code',	'Municipio'], how='inner')
worldclim_df

,State code,Departamento,Municipality code,cod_mun,Municipio,Elevation,PRECIPITATION_jan_12,PRECIPITATION_feb_12,PRECIPITATION_mar_12,PRECIPITATION_apr_12,...,TEMPERATURE_mar_18,TEMPERATURE_apr_18,TEMPERATURE_may_18,TEMPERATURE_jun_18,TEMPERATURE_jul_18,TEMPERATURE_aug_18,TEMPERATURE_sep_18,TEMPERATURE_oct_18,TEMPERATURE_nov_18,TEMPERATURE_dec_18
0,5,ANTIOQUIA,5001,1,MEDELLIN,1650.0,143.996338,84.448479,182.468307,333.664246,...,21.726171,21.124271,21.037365,21.457151,21.952168,21.719432,21.347202,20.748416,20.886703,20.936353
1,5,ANTIOQUIA,5002,2,ABEJORRAL,2150.0,160.942566,106.062065,195.236008,335.972321,...,17.169984,16.471953,16.495468,17.036293,17.063302,17.103385,17.011875,16.495094,16.674297,16.627245
2,5,ANTIOQUIA,5004,4,ABRIAQUI,2162.0,111.156319,63.352127,139.529083,264.172241,...,17.833994,17.378247,17.221657,17.529025,17.843157,17.512112,17.356325,16.911367,17.231535,17.080420
3,5,ANTIOQUIA,5021,21,ALEJANDRIA,1612.0,150.545135,83.663269,196.101776,379.806580,...,21.489558,20.985991,21.025772,21.377411,21.652374,21.425886,21.230342,20.725872,20.687894,20.574121
4,5,ANTIOQUIA,5030,30,AMAGA,1537.0,134.874725,88.863426,153.000458,319.132904,...,21.648314,21.020582,20.880769,21.149931,21.560988,21.380573,21.026458,20.558420,20.625113,20.717262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,97,VAUPES,97889,889,YAVARATE,163.0,246.043457,293.505249,407.725311,365.653198,...,26.505539,25.702706,25.167677,25.276139,25.008356,25.352882,26.116107,26.381042,26.529586,26.300149
1117,99,VICHADA,99001,1,PUERTO CARRENO,66.0,4.852512,64.169716,19.765818,137.477249,...,29.914727,28.625936,27.245942,26.710096,26.794482,27.001324,27.557754,27.757870,28.391361,28.290137
1118,99,VICHADA,99524,524,LA PRIMAVERA,98.0,8.818299,24.708885,37.555386,201.510422,...,29.391974,27.948265,26.860780,26.380163,26.470571,26.864957,27.489720,27.587379,28.106454,28.010822
1119,99,VICHADA,99624,624,SANTA ROSALIA,142.0,17.106863,27.472258,71.874939,257.697968,...,28.906054,27.354861,26.131048,25.852802,25.822849,26.348023,27.013428,27.146027,27.544563,27.512444
1120,99,VICHADA,99773,773,CUMARIBO,159.0,21.897491,38.989922,60.883514,170.462570,...,28.155295,26.945577,26.048269,25.827329,25.908164,26.096456,26.865039,26.887561,27.399683,27.309817

# Censo Nacional Agropecuario (Cauca)

In [41]:
agriulture = pd.read_csv(path + 'Censo Nacional Agropecuario/Censo_Output/censo_agropecuario.csv', encoding='latin1', sep=',')
agriulture.rename(columns={'P_MUNIC':'Municipality code'}, inplace=True) 
agriulture

,Municipality code,inundacion,exceso_lluvia,sequia,total_riesgos,Credito_Solicitado,Credito_Aprobado,P_S6P71,total_agro,Credito_banco,...,agua_lluvia,agua_fuente_natural,agua_no_acceso,agua_acueducto,agua_carrotanque,distrito_riego,no_agua_contaminacion,no_agua_desastres_naturales,no_agua_sequia,no_agua_fallos_servicio
0,19001,0,7,17,14633,775.0,684.0,5958.0,5420,702.0,...,615.0,2553.0,405.0,1635.0,34.0,10.0,200.0,517.0,1861.0,517.0
1,19022,0,12,87,11335,204.0,159.0,1322.0,10257,156.0,...,4069.0,3951.0,2380.0,71.0,4.0,77.0,154.0,265.0,4688.0,265.0
2,19050,0,0,0,8134,416.0,303.0,3942.0,3736,307.0,...,342.0,2577.0,386.0,469.0,14.0,19.0,293.0,146.0,813.0,146.0
3,19075,0,0,0,9995,559.0,497.0,840.0,4419,497.0,...,810.0,3102.0,458.0,24.0,1.0,25.0,174.0,231.0,3142.0,231.0
4,19100,0,4,10,20519,537.0,466.0,1370.0,23205,484.0,...,1814.0,10235.0,9922.0,1011.0,33.0,89.0,179.0,659.0,11818.0,659.0
5,19110,0,0,8,16887,585.0,454.0,10183.0,6474,441.0,...,1976.0,3200.0,825.0,542.0,6.0,9.0,325.0,177.0,3104.0,177.0
6,19130,0,0,0,11519,791.0,706.0,2825.0,4961,727.0,...,233.0,3686.0,653.0,497.0,6.0,4.0,278.0,220.0,1937.0,220.0
7,19137,0,1,4,12295,898.0,829.0,3481.0,6261,860.0,...,855.0,4245.0,916.0,130.0,8.0,18.0,119.0,304.0,2446.0,304.0
8,19142,16,13,58,10201,575.0,515.0,3649.0,4116,483.0,...,1282.0,1971.0,723.0,463.0,6.0,31.0,234.0,343.0,1976.0,343.0
9,19212,0,0,0,4172,111.0,97.0,1347.0,2514,35.0,...,422.0,1186.0,817.0,55.0,1.0,0.0,64.0,59.0,914.0,59.0
10,19256,0,5,1,38316,1716.0,1469.0,10925.0,12668,1532.0,...,1161.0,6426.0,2195.0,3065.0,39.0,58.0,346.0,620.0,3845.0,620.0
11,19290,0,0,2,5474,190.0,174.0,797.0,1612,175.0,...,82.0,707.0,419.0,439.0,2.0,0.0,43.0,33.0,527.0,33.0
12,19300,0,0,2,9057,244.0,219.0,182.0,2797,116.0,...,1694.0,562.0,357.0,121.0,3.0,12.0,9.0,42.0,929.0,42.0
13,19318,14,0,0,24773,524.0,463.0,110.0,3478,464.0,...,2159.0,2319.0,132.0,112.0,3.0,15.0,173.0,91.0,168.0,91.0
14,19355,0,0,1,14004,775.0,705.0,1452.0,5232,663.0,...,55.0,3837.0,944.0,317.0,1.0,10.0,247.0,1176.0,843.0,1176.0
15,19364,0,18,49,21965,348.0,307.0,1277.0,2824,298.0,...,155.0,1958.0,418.0,276.0,3.0,2.0,59.0,316.0,945.0,316.0
16,19392,0,0,1,5863,457.0,378.0,1534.0,2585,383.0,...,26.0,1442.0,521.0,580.0,8.0,0.0,56.0,192.0,1120.0,192.0
17,19397,0,0,12,6194,297.0,257.0,1308.0,5309,248.0,...,45.0,3581.0,1075.0,174.0,4.0,1.0,106.0,285.0,1231.0,285.0
18,19418,6,0,4,27386,107.0,71.0,464.0,4286,70.0,...,2088.0,2919.0,195.0,73.0,4.0,22.0,577.0,254.0,205.0,254.0
19,19450,0,0,18,3794,384.0,352.0,1689.0,5146,360.0,...,1120.0,2248.0,1293.0,601.0,9.0,265.0,69.0,33.0,3864.0,33.0
20,19455,4,0,10,5130,460.0,394.0,1295.0,1820,196.0,...,112.0,1037.0,355.0,148.0,2.0,4.0,22.0,57.0,426.0,57.0
21,19473,0,4,3,16451,996.0,780.0,5323.0,6428,773.0,...,656.0,3906.0,885.0,1284.0,25.0,13.0,139.0,201.0,2160.0,201.0
22,19513,0,0,0,3742,476.0,461.0,0.0,1535,85.0,...,853.0,607.0,79.0,70.0,1.0,6.0,16.0,301.0,433.0,301.0
23,19517,0,3,1,16948,661.0,598.0,3661.0,3778,600.0,...,271.0,1865.0,304.0,1324.0,13.0,39.0,169.0,672.0,739.0,672.0
24,19532,0,1,27,6615,428.0,344.0,4167.0,4770,351.0,...,343.0,3553.0,415.0,574.0,19.0,6.0,422.0,177.0,3114.0,177.0
25,19533,0,0,0,4017,91.0,79.0,2056.0,719,77.0,...,21.0,581.0,57.0,63.0,1.0,0.0,111.0,25.0,44.0,25.0
26,19548,0,0,0,12492,1024.0,932.0,1611.0,6670,981.0,...,514.0,1918.0,1675.0,2793.0,76.0,35.0,230.0,227.0,1351.0,227.0
27,19573,0,2,7,2374,211.0,204.0,115.0,764,58.0,...,282.0,353.0,33.0,56.0,2.0,1.0,16.0,20.0,308.0,20.0
28,19585,4,132,89,6891,517.0,453.0,2078.0,2492,452.0,...,46.0,2111.0,117.0,105.0,1.0,20.0,98.0,241.0,806.0,241.0
29,19622,0,0,0,8185,556.0,524.0,2534.0,3426,536.0,...,121.0,2719.0,487.0,52.0,1.0,3.0,74.0,219.0,1504.0,219.0
30,19693,0,9,34,4212,200.0,148.0,1354.0,6386,140.0,...,308.0,3183.0,2405.0,360.0,3.0,1.0,35.0,138.0,3931.0,138.0
31,19698,0,0,0,15599,1076.0,976.0,5560.0,5275,924.0,...,456.0,3702.0,435.0,616.0,13.0,8.0,245.0,97.0,1765.0,97.0
32,19701,0,0,0,7865,115.0,65.0,3019.0,2123,69.0,...,148.0,1717.0,121.0,77.0,0.0,0.0,26.0,338.0,197.0,338.0
33,19743,0,11,51,21900,860.0,753.0,5059.0,8213,766.0,...,1077.0,4658.0,2163.0,330.0,7.0,20.0,356.0,518.0,2388.0,518.0
34,19760,9,126,85,14591,559.0,471.0,4065.0,4834,488.0,...,98.0,3691.0,377.0,778.0,15.0,43.0,372.0,862.0,1702.0,862.0
35,19780,0,0,0,9265,468.0,405.0,2578.0,3774,410.0,...,712.0,2001.0,872.0,89.0,2.0,8.0,105.0,119.0,1454.0,119.0
36,19785,0,0,0,2219,191.0,169.0,625.0,2081,170.0,...,271.0,1051.0,629.0,60.0,2.0,0.0,57.0,67.0,905.0,67.0
37,19807,0,2,4,18785,1378.0,1245.0,3752.0,5849,1285.0,...,1908.0,1630.0,780.0,2093.0,35.0,161.0,206.0,375.0,990.0,375.0
38,19809,0,0,0,24071,252.0,164.0,382.0,4186,160.0,...,2122.0,2955.0,160.0,138.0,1.0,9.0,1635.0,257.0,577.0,257.0
39,19821,0,15,9,19953,545.0,463.0,2510.0,4161,381.0,...,269.0,3027.0,644.0,158.0,3.0,8.0,322.0,615.0,1619.0,615.0
40,19824,0,0,17,18031,738.0,653.0,3191.0,4151,651.0,...,420.0,2806.0,648.0,83.0,3.0,103.0,169.0,214.0,2092.0,214.0
41,19845,0,0,0,2607,80.0,73.0,269.0,1535,20.0,...,518.0,405.0,196.0,23.0,0.0,4.0,4.0,53.0,645.0,53.0

# ENSIN (Cauca)

In [42]:
ENSIN = pd.read_csv(path + 'ENSIN/ENSIN output/ENSIN_final.csv', encoding='latin1', sep=',')
ENSIN.rename(columns={'c_mpio':'Municipality code'}, inplace=True) 
ENSIN

,Municipality code,SA10_1,SA10_2,SA10_3,SA10_4,seguridad,marginal,inseguridad,menor_calidad,disminuir_porciones,...,Plat_Tub,Frutas,Azucar,Grasas,Carnes,Lacteos,Cereales,Verduras,Legumbres,respuestas_pisnsp
0,19001,3064.0,544.0,1216.0,544.0,3736.0,2520.0,5368.0,1216.0,544.0,...,5488.0,4128.0,5488.0,0.0,4672.0,5488.0,5488.0,4128.0,3736.0,5488
1,19075,11642.0,0.0,662.0,3966.0,12506.0,0.0,16270.0,11642.0,11186.0,...,18148.0,16906.0,18364.0,0.0,18364.0,10264.0,18364.0,13066.0,10364.0,18364
2,19100,4457.0,738.0,1113.0,492.0,4717.0,2866.0,6800.0,1032.0,998.0,...,3819.0,3870.0,5691.0,0.0,4698.0,4958.0,5691.0,3405.0,3592.0,5691
3,19517,6408.0,1368.0,4176.0,1368.0,6408.0,2232.0,13320.0,2212.0,0.0,...,18818.0,16754.0,19586.0,1560.0,19586.0,16328.0,19586.0,16670.0,10488.0,19586
4,19532,11106.0,1376.0,7736.0,6760.0,11106.0,2234.0,26978.0,8336.0,5424.0,...,10404.0,8682.0,11538.0,2556.0,11718.0,10518.0,11718.0,5842.0,3636.0,11718
5,19693,19636.0,8257.0,16549.0,19405.0,20221.0,816.0,63847.0,17496.0,10744.0,...,22396.0,21421.0,22396.0,4920.0,21340.0,18021.0,22981.0,19656.0,16060.0,22981
6,19698,224.0,0.0,0.0,0.0,224.0,0.0,224.0,0.0,0.0,...,224.0,224.0,224.0,0.0,224.0,224.0,224.0,224.0,224.0,224
7,19807,4750.0,0.0,0.0,0.0,4750.0,4680.0,4750.0,4750.0,70.0,...,9596.0,9400.0,11846.0,0.0,11846.0,11516.0,11846.0,10080.0,4214.0,11846
8,19809,9347.0,9347.0,9347.0,9347.0,9347.0,0.0,37388.0,0.0,0.0,...,5227.0,9347.0,9347.0,5860.0,8858.0,9347.0,9347.0,3076.0,2963.0,9347

# Merge All

In [43]:
# MPM + Sociodemographic
mpm_Sociodemographic = merge_two_df(sociodemographic_df, mpm_df, how='inner')
mpm_Sociodemographic

,State code,State,Municipality code,Municipality,Population 2015,Population 2016,Population 2017,Population 2018,Population 2019,Age 0-4 (%),...,SAFAM_CPRD,SAS_TOT,SAS_CAB,SAS_CPRD,TRINF_TOT,TRINF_CAB,TRINF_CPRD,TRIML_TOT,TRIML_CAB,TRIML_CPRD
0,5,Antioquia,5001,Medellín,2431666,2420516,2414616,2427129,2483545,5.16,...,16.9,15.9,15.9,15.5,0.5,0.5,1.1,71.0,70.9,77.3
1,5,Antioquia,5002,Abejorral,19897,19979,20047,20367,20258,5.24,...,54.8,8.8,11.8,6.6,3.6,1.5,5.2,87.5,80.4,92.7
2,5,Antioquia,5004,Abriaquí,2514,2539,2593,2695,2710,6.07,...,54.5,11.7,15.8,9.2,1.2,0.7,1.5,87.6,83.8,90.0
3,5,Antioquia,5021,Alejandría,4511,4543,4570,4657,4669,6.59,...,65.3,11.0,11.8,9.8,1.5,0.9,2.5,87.1,84.7,90.7
4,5,Antioquia,5030,Amagá,28691,29006,29429,30227,30777,5.42,...,7.9,14.1,14.5,13.6,0.8,0.6,0.9,69.5,69.1,69.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,97,Vaupés,97889,Yavaraté,1212,1073,1027,1048,1067,5.03,...,86.0,35.5,0.0,35.5,1.1,0.0,1.1,98.9,0.0,98.9
1118,99,Vichada,99001,Puerto Carreño,20319,20921,21087,20936,20474,10.61,...,54.0,28.3,25.4,36.4,1.6,1.6,1.5,84.9,82.6,91.4
1119,99,Vichada,99524,La Primavera,9694,10098,10233,10122,9799,10.37,...,27.2,30.4,28.4,33.6,1.4,1.1,1.7,87.5,86.4,89.3
1120,99,Vichada,99624,Santa Rosalía,4551,4296,4083,4059,4130,9.34,...,30.2,24.2,20.8,30.8,1.1,1.1,1.1,76.7,75.5,79.1
1121,99,Vichada,99773,Cumaribo,51719,57693,65161,72691,76196,14.09,...,86.3,44.6,23.4,46.8,1.0,0.6,1.1,96.5,84.7,97.7

In [44]:
# MPM + Sociodemographic + Wclim
mpm_Sociodemographic_Wclim = merge_two_df(mpm_Sociodemographic, worldclim_df, how='inner')
mpm_Sociodemographic_Wclim

,State code,State,Municipality code,Municipality,Population 2015,Population 2016,Population 2017,Population 2018,Population 2019,Age 0-4 (%),...,TEMPERATURE_mar_18,TEMPERATURE_apr_18,TEMPERATURE_may_18,TEMPERATURE_jun_18,TEMPERATURE_jul_18,TEMPERATURE_aug_18,TEMPERATURE_sep_18,TEMPERATURE_oct_18,TEMPERATURE_nov_18,TEMPERATURE_dec_18
0,5,Antioquia,5001,Medellín,2431666,2420516,2414616,2427129,2483545,5.16,...,21.726171,21.124271,21.037365,21.457151,21.952168,21.719432,21.347202,20.748416,20.886703,20.936353
1,5,Antioquia,5002,Abejorral,19897,19979,20047,20367,20258,5.24,...,17.169984,16.471953,16.495468,17.036293,17.063302,17.103385,17.011875,16.495094,16.674297,16.627245
2,5,Antioquia,5004,Abriaquí,2514,2539,2593,2695,2710,6.07,...,17.833994,17.378247,17.221657,17.529025,17.843157,17.512112,17.356325,16.911367,17.231535,17.080420
3,5,Antioquia,5021,Alejandría,4511,4543,4570,4657,4669,6.59,...,21.489558,20.985991,21.025772,21.377411,21.652374,21.425886,21.230342,20.725872,20.687894,20.574121
4,5,Antioquia,5030,Amagá,28691,29006,29429,30227,30777,5.42,...,21.648314,21.020582,20.880769,21.149931,21.560988,21.380573,21.026458,20.558420,20.625113,20.717262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116,97,Vaupés,97889,Yavaraté,1212,1073,1027,1048,1067,5.03,...,26.505539,25.702706,25.167677,25.276139,25.008356,25.352882,26.116107,26.381042,26.529586,26.300149
1117,99,Vichada,99001,Puerto Carreño,20319,20921,21087,20936,20474,10.61,...,29.914727,28.625936,27.245942,26.710096,26.794482,27.001324,27.557754,27.757870,28.391361,28.290137
1118,99,Vichada,99524,La Primavera,9694,10098,10233,10122,9799,10.37,...,29.391974,27.948265,26.860780,26.380163,26.470571,26.864957,27.489720,27.587379,28.106454,28.010822
1119,99,Vichada,99624,Santa Rosalía,4551,4296,4083,4059,4130,9.34,...,28.906054,27.354861,26.131048,25.852802,25.822849,26.348023,27.013428,27.146027,27.544563,27.512444
1120,99,Vichada,99773,Cumaribo,51719,57693,65161,72691,76196,14.09,...,28.155295,26.945577,26.048269,25.827329,25.908164,26.096456,26.865039,26.887561,27.399683,27.309817

In [45]:
# MPM + Sociodemographic + Wclim = Sivigila
mpm_Sociodemographic_Wclim_Sivigila = merge_two_df(mpm_Sociodemographic_Wclim, desnutricion_df, how='inner')
mpm_Sociodemographic_Wclim_Sivigila

,State code,State,Municipality code,Municipality,Population 2015,Population 2016,Population 2017,Population 2018,Population 2019,Age 0-4 (%),...,cases_MortalidadDesnutricion_2019_week_43,cases_MortalidadDesnutricion_2019_week_44,cases_MortalidadDesnutricion_2019_week_45,cases_MortalidadDesnutricion_2019_week_46,cases_MortalidadDesnutricion_2019_week_47,cases_MortalidadDesnutricion_2019_week_48,cases_MortalidadDesnutricion_2019_week_49,cases_MortalidadDesnutricion_2019_week_50,cases_MortalidadDesnutricion_2019_week_51,cases_MortalidadDesnutricion_2019_week_52
0,5,Antioquia,5001,Medellín,2431666,2420516,2414616,2427129,2483545,5.16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5,Antioquia,5002,Abejorral,19897,19979,20047,20367,20258,5.24,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5,Antioquia,5030,Amagá,28691,29006,29429,30227,30777,5.42,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5,Antioquia,5031,Amalfi,24444,24794,25205,25962,26552,6.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Antioquia,5034,Andes,42495,42564,42614,43269,43713,5.79,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042,97,Vaupés,97889,Yavaraté,1212,1073,1027,1048,1067,5.03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1043,99,Vichada,99001,Puerto Carreño,20319,20921,21087,20936,20474,10.61,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1044,99,Vichada,99524,La Primavera,9694,10098,10233,10122,9799,10.37,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1045,99,Vichada,99624,Santa Rosalía,4551,4296,4083,4059,4130,9.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1046,99,Vichada,99773,Cumaribo,51719,57693,65161,72691,76196,14.09,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [46]:
mpm_Sociodemographic_Wclim_Sivigila.to_csv(path + 'OutputDataset/' +  'SeguridadAlimentariaV1.csv')

# Merge all with Agricultute and ENSIN (Just for Cauca)

In [47]:
mpm_Sociodemographic_Wclim_Sivigila_Agriculture = agriulture.merge(mpm_Sociodemographic_Wclim_Sivigila, on=['Municipality code'], how='inner')
mpm_Sociodemographic_Wclim_Sivigila_Agriculture

,Municipality code,inundacion,exceso_lluvia,sequia,total_riesgos,Credito_Solicitado,Credito_Aprobado,P_S6P71,total_agro,Credito_banco,...,cases_MortalidadDesnutricion_2019_week_43,cases_MortalidadDesnutricion_2019_week_44,cases_MortalidadDesnutricion_2019_week_45,cases_MortalidadDesnutricion_2019_week_46,cases_MortalidadDesnutricion_2019_week_47,cases_MortalidadDesnutricion_2019_week_48,cases_MortalidadDesnutricion_2019_week_49,cases_MortalidadDesnutricion_2019_week_50,cases_MortalidadDesnutricion_2019_week_51,cases_MortalidadDesnutricion_2019_week_52
0,19001,0,7,17,14633,775.0,684.0,5958.0,5420,702.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,19022,0,12,87,11335,204.0,159.0,1322.0,10257,156.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,19050,0,0,0,8134,416.0,303.0,3942.0,3736,307.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,19075,0,0,0,9995,559.0,497.0,840.0,4419,497.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,19100,0,4,10,20519,537.0,466.0,1370.0,23205,484.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,19110,0,0,8,16887,585.0,454.0,10183.0,6474,441.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,19130,0,0,0,11519,791.0,706.0,2825.0,4961,727.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,19137,0,1,4,12295,898.0,829.0,3481.0,6261,860.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,19142,16,13,58,10201,575.0,515.0,3649.0,4116,483.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,19212,0,0,0,4172,111.0,97.0,1347.0,2514,35.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,19256,0,5,1,38316,1716.0,1469.0,10925.0,12668,1532.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,19290,0,0,2,5474,190.0,174.0,797.0,1612,175.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,19300,0,0,2,9057,244.0,219.0,182.0,2797,116.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,19318,14,0,0,24773,524.0,463.0,110.0,3478,464.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,19355,0,0,1,14004,775.0,705.0,1452.0,5232,663.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,19364,0,18,49,21965,348.0,307.0,1277.0,2824,298.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,19392,0,0,1,5863,457.0,378.0,1534.0,2585,383.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,19397,0,0,12,6194,297.0,257.0,1308.0,5309,248.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,19418,6,0,4,27386,107.0,71.0,464.0,4286,70.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,19450,0,0,18,3794,384.0,352.0,1689.0,5146,360.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,19455,4,0,10,5130,460.0,394.0,1295.0,1820,196.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,19473,0,4,3,16451,996.0,780.0,5323.0,6428,773.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,19513,0,0,0,3742,476.0,461.0,0.0,1535,85.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,19517,0,3,1,16948,661.0,598.0,3661.0,3778,600.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,19532,0,1,27,6615,428.0,344.0,4167.0,4770,351.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,19533,0,0,0,4017,91.0,79.0,2056.0,719,77.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,19548,0,0,0,12492,1024.0,932.0,1611.0,6670,981.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,19573,0,2,7,2374,211.0,204.0,115.0,764,58.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,19585,4,132,89,6891,517.0,453.0,2078.0,2492,452.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,19622,0,0,0,8185,556.0,524.0,2534.0,3426,536.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,19693,0,9,34,4212,200.0,148.0,1354.0,6386,140.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,19698,0,0,0,15599,1076.0,976.0,5560.0,5275,924.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,19701,0,0,0,7865,115.0,65.0,3019.0,2123,69.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,19743,0,11,51,21900,860.0,753.0,5059.0,8213,766.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,19760,9,126,85,14591,559.0,471.0,4065.0,4834,488.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,19780,0,0,0,9265,468.0,405.0,2578.0,3774,410.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,19785,0,0,0,2219,191.0,169.0,625.0,2081,170.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,19807,0,2,4,18785,1378.0,1245.0,3752.0,5849,1285.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,19809,0,0,0,24071,252.0,164.0,382.0,4186,160.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,19821,0,15,9,19953,545.0,463.0,2510.0,4161,381.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,19824,0,0,17,18031,738.0,653.0,3191.0,4151,651.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,19845,0,0,0,2607,80.0,73.0,269.0,1535,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [48]:
mpm_Sociodemographic_Wclim_Sivigila_Agriculture_Ensin = ENSIN.merge(mpm_Sociodemographic_Wclim_Sivigila_Agriculture, on=['Municipality code'], how='inner')
mpm_Sociodemographic_Wclim_Sivigila_Agriculture_Ensin

,Municipality code,SA10_1,SA10_2,SA10_3,SA10_4,seguridad,marginal,inseguridad,menor_calidad,disminuir_porciones,...,cases_MortalidadDesnutricion_2019_week_43,cases_MortalidadDesnutricion_2019_week_44,cases_MortalidadDesnutricion_2019_week_45,cases_MortalidadDesnutricion_2019_week_46,cases_MortalidadDesnutricion_2019_week_47,cases_MortalidadDesnutricion_2019_week_48,cases_MortalidadDesnutricion_2019_week_49,cases_MortalidadDesnutricion_2019_week_50,cases_MortalidadDesnutricion_2019_week_51,cases_MortalidadDesnutricion_2019_week_52
0,19001,3064.0,544.0,1216.0,544.0,3736.0,2520.0,5368.0,1216.0,544.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,19075,11642.0,0.0,662.0,3966.0,12506.0,0.0,16270.0,11642.0,11186.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,19100,4457.0,738.0,1113.0,492.0,4717.0,2866.0,6800.0,1032.0,998.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,19517,6408.0,1368.0,4176.0,1368.0,6408.0,2232.0,13320.0,2212.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,19532,11106.0,1376.0,7736.0,6760.0,11106.0,2234.0,26978.0,8336.0,5424.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,19693,19636.0,8257.0,16549.0,19405.0,20221.0,816.0,63847.0,17496.0,10744.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,19698,224.0,0.0,0.0,0.0,224.0,0.0,224.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,19807,4750.0,0.0,0.0,0.0,4750.0,4680.0,4750.0,4750.0,70.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,19809,9347.0,9347.0,9347.0,9347.0,9347.0,0.0,37388.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
# Final Dataset to csv
mpm_Sociodemographic_Wclim_Sivigila_Agriculture_Ensin.to_csv(path + 'OutputDataset/' +  'SeguridadAlimentariaCaucaFinal.csv')